"""empty message

Revision ID: 0df3a769a697
Revises: 7ebc4efa2107
Create Date: 2024-12-01 18:03:44.358812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df3a769a697'
down_revision: Union[str, None] = '7ebc4efa2107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storePages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guildID', sa.BigInteger(), nullable=True),
    sa.Column('storeName', sa.String(), nullable=True),
    sa.Column('storeLink', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guildID'], ['guildSettings.guildID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Economy', 'uid',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('Levels', 'uid',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('Users', sa.Column('warnings', sa.Integer(), nullable=True))
    op.alter_column('Users', 'uid',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('guildSettings', sa.Column('lotterypot', sa.Integer(), nullable=True))
    op.alter_column('guildSettings', 'ownerID',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'guildSettings', ['guildID'])
    op.drop_column('guildSettings', 'defacedCurrenty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guildSettings', sa.Column('defacedCurrenty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guildSettings', type_='unique') # type: ignore
    op.alter_column('guildSettings', 'ownerID',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('guildSettings', 'lotterypot')
    op.alter_column('Users', 'uid',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('Users', 'warnings')
    op.alter_column('Levels', 'uid',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Economy', 'uid',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('storePages')
    # ### end Alembic commands ###
