[DEFAULT]
token = "MTI5NDkwOTk2NDQ4OTMyNjU5Mg.GNwqVq.R0_LURf9dcjRFUWFhixGNG6s7tDsBP4ZZUoHD8"

[DATABASE]
engine = "postgresql"
host = "0.0.0.0"
port = 5432
username = "postgres"
password = "postgres"
database = "testdb"

[VERSION]
version = "0.4"
major = 0
minor = 4
branch = "dev"

[MESSAGE]
activity = "Watching A load of Game Developers"
