[DEFAULT]
token = "MTI5NDkwOTk2NDQ4OTMyNjU5Mg.GNwqVq.R0_LURf9dcjRFUWFhixGNG6s7tDsBP4ZZUoHD8"

[DATABASE]
engine = "postgresql"
host = "0.0.0.0"
port = 27017
username = "root"
password = "example"
database = "testdb"
[VERSION]
version = "0.0.1-dev"

[MESSAGE]
activity = "Watching A load of Game Developers"
