name: MyPy Checks
on:
  workflow_call:


jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
        architecture: [x64, arm64, x86]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture:  ${{ matrix.architexture }}
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false
