name: 🔗 GHA
on: [push, pull_request]


jobs:
  mypy-checks:
    name: Ensure type safety
    uses: ./.github/workflows/mypy-tests.yml

  test-bot:
    name: Test Hikari
    needs: python-tests
    uses: ./.github/workflows/hikari-test.yml

  push-docker:
    name: Build and Push docker
    needs: test-bot
    uses: ./.github/workflows/docker.yml

